---
  - name: ensure git is the last version
    apt: name=git state=latest

  - name: ensure vim is the last version
    apt: name=vim state=latest

  - name: ensure curl is the last version
    apt: name=curl state=latest